In [7]:
import torch
import torch.nn as nn
import random
random.seed(42)

In [39]:
# X = torch.randn((4, 8))
# logits = torch.randn((8,4))  #Batch_size, num_classes
logits = torch.randn((1,4))  #Batch_size, num_classes
softmax = nn.Softmax(dim=1)
# pred_y = softmax(logits)
pred_y = logits
print(pred_y, pred_y.shape)
print(torch.sum(pred_y, axis = 1))
print(pred_y)
print(logits)

tensor([[-0.5061,  1.4615, -0.3117, -1.7064]]) torch.Size([1, 4])
tensor([-1.0627])
tensor([[-0.5061,  1.4615, -0.3117, -1.7064]])
tensor([[-0.5061,  1.4615, -0.3117, -1.7064]])


In [40]:

# true_label = torch.randint(4, (8,), dtype=torch.int64)
true_label = torch.randint(4, (1,), dtype=torch.int64)
pred_label = pred_y
print(f'true label: {true_label}, {true_label.shape}')
print(f'pred label: {pred_label}, {pred_label.shape}')

true label: tensor([0]), torch.Size([1])
pred label: tensor([[-0.5061,  1.4615, -0.3117, -1.7064]]), torch.Size([1, 4])


In [41]:
loss_fn = nn.CrossEntropyLoss()
loss_fn(pred_y, true_label)

tensor(2.2689)

In [42]:
pred_sm = softmax(pred_label)
pred_sm

tensor([[0.1034, 0.7398, 0.1256, 0.0311]])

In [43]:
torch.log(pred_sm)

tensor([[-2.2689, -0.3014, -2.0745, -3.4692]])